### ISSUE TITLE
Installing Zonation without installer

### ISSUE THREAD

**Issue by jackevau** [zonationteam/Zonation5#3]
Hi, is there any way to install Zonation v5 without using the installer (Z5setup) file? Can I use the source code provided (z5src-v1.0)? Windows 64, currently workplace proxy access is not allowed, even for administrators. 

(Note: This is not an issue. This is a query. Feel free to remove if not the right forum)

Thanks,

**Comment by kirahvi** [comment]
Hi. I'm not sure what you mean by "proxy access", can you not download the zip file containing the installer, or can you not run the installer because it requires administrator rights? Unfortunately in Windows, admin rights are required to install, and compiling the code would also require installation of various tools that need admin rights to install. The Linux version can be run directly without installation, if you have access to a Linux machine with some reasonably recent Linux distribution.

**Comment by jackevau** [comment]
Hi, thanks for the reply. This is now resolved. Further instructions for administrator rights allowed the override of the Windows Defender (which identified the Z5Setup as Unknown publisher), which then allowed the installer to work.
