### ISSUE TITLE
treatment of zero range layers

### ISSUE THREAD

**Issue by jackevau** [zonationteam/Zonation5#6]
Have a potential issue where we have "zero value range layers" no data values are included in the Zonation run and incorporated into the ranking. The run seems to still consider them even with excluding zero values "zero mode = none". 

This was identified initially in the group performance curve outputs which the mean/weighted mean for the specific group that contains the zero range was lower than 1 starting coverage.  (see image below)

![image (6)](https://github.com/zonationteam/Zonation5/assets/97150770/488fe0d8-4942-404a-9ad6-df24459227a8)

Zonation also initially identified these in the log, and labelled them as warnings correctly and proceeded as normal. Condition was used in the run but set to renormalization, so the lower starting coverage was not affected by condition layers. Hierarchic mask was also applied which doesn't affect the coverage starting point.

To test the issue, the same run was applied without the identified zero range feature layers, and this corrected the performance curve for the groups back to starting coverage of 1. (See image below)

![image (3)](https://github.com/zonationteam/Zonation5/assets/97150770/706bad34-9180-4817-b1e0-7267cd19e4bb)

A difference was run over both prioritisation ranking processes which identified only small shifts mostly (within 1%), but an absolute shift of 12%.
![image (4)](https://github.com/zonationteam/Zonation5/assets/97150770/89c9e028-83fc-435c-9393-d1cdd2ea3f82)

Processing steps are being reviewed as to exclude these entirely, however documentation says Zonation excludes zero range layers. There is no other setting that excludes these features from the analysis run.

Any suggestions?

Thanks

**Comment by kirahvi** [comment]
When you get the warning "Layer X.tif value range is zero" from some layers in the analysis, Zonation 5 v1.0 doesn't remove the layers from analysis. They shouldn't affect the ranking result, but do affect the mean curves. This will change in v2.0, but for now, the layers must be removed manually, if needed.

But if I understand correctly, you're saying that even the ranking result was changed, after you removed the zero layers, and did no other changes in the setup? This shouldn't happen, and I wasn't able to reproduce that. Some more information about the setup is needed if this is the case.

The "zero mode" setting is unrelated to this, it doesn't cause removal of layers in any case.

**Comment by jackevau** [comment]
Unfortunately it seems I still am getting a different ranking result, however not consistently across all parameters and certainly not ruling something I've missed! It is a complex run with over 500 layers, hierarchic mask, condition, weights and weight groups applied. 

I still get a difference when run with all parameters included. However, the issue seems to be when applying weight groups. when I reran the analysis using all other parameters separately singled out, I did not get a difference. 

So far I trialled the following:
0. All parameters applied (normal run): **difference**
1.unconstrained (no other parameters): _**no difference*_*
2. weights applied: _**no difference**_
3. weight and weight group (WG) included: **difference**
4. condition only, no weights: _**no difference**_
5. hierarchic mask only, no weights: _**no difference**_

![image (7)](https://github.com/zonationteam/Zonation5/assets/97150770/e756a262-0aa1-4696-a005-f68d91de4f6d)

I can send copies of the log texts, settings, features and wg files if needed.

thanks

**Comment by kirahvi** [comment]
If you have a weight group, and some of the zero range layers are in such group, then removing those zero layers can cause some change in the calculation of the weights of the remaining layers in that weight group because the sum of the weights will be different. Then it makes sense that if weights are enabled during the run, also the ranking result will be different after removing the zero layers. 

So are some of the zero layers in the analysis in weight groups that have also nonzero layers? If so, this is expected behavior.

**Comment by jackevau** [comment]
Hi Thanks for responding during a busy time of the year. I was suspecting this is the cause. Yes that are in a weight group as all features are assigned in bulk and the zero range matter isn't picked up until a Zonation run. It was found these features may have data in the rectangular extent of the region, but not within the analysis area (the region itself). True no data (no data at all in the extent) was excluded entirely. We have resolved this, but a process may be need to be added as a failsafe, to assign them as (wgrp = -1) if they have been flagged .

Can I suggest, even though we are removing these, is it possible to consider ways to exclude these entirely from rankings in V5.2, even if they are assigned a weight group?  This exclusion could be done, I assume, either by the code (by removing them from analysis - if flagged as zero range), or, at least, manual documentation notifying they are still included in the ranking regardless if they are assigned in a weight group. I only ask because it is assumed by the current manual that they do not affect ranking at all (which is true except if they are assigned a wgrp).

Thanks

**Comment by kirahvi** [comment]
V2.0 of Zonation 5 will remove zero layers completely from the analysis when such are found. This may change the weight calculations, if weight groups are used, because each weight group's aggregate weight will be distributed to the remaining layers, which are now fewer in number. (The aggregate weight of a weight group is not changed.)

You're right that the manual doesn't currently mention the consequences of those zero layers to the curves or weight groups. We'll add some text about the removal of zero layers to the next version. Ideally, zero-layers are not entered into analysis to begin with. Even so, the use  of an analysis area mask or some transforms can lead to layers becoming zero during preprocessing.
